// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_cpu.Services;

#nullable disable

namespace api_cpu.Migrations
{
    [DbContext(typeof(AppDbContexte))]
    partial class AppDbContexteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_cpu.Models.Cpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Famille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("famille");

                    b.Property<float>("Frequence")
                        .HasColumnType("real")
                        .HasColumnName("frequence");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marque");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modele");

                    b.Property<int>("Prix")
                        .HasColumnType("int")
                        .HasColumnName("prix");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_cpus");

                    b.ToTable("cpus", (string)null);
                });

            modelBuilder.Entity("api_cpu.Models.CpuProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CpuId")
                        .HasColumnType("int")
                        .HasColumnName("cpu_id");

                    b.Property<int>("DureeProd")
                        .HasColumnType("int")
                        .HasColumnName("duree_prod");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("pk_cpu_production");

                    b.HasIndex("CpuId")
                        .HasDatabaseName("ix_cpu_production_cpu_id");

                    b.ToTable("cpu_production", (string)null);
                });

            modelBuilder.Entity("api_cpu.Models.CpuProduction", b =>
                {
                    b.HasOne("api_cpu.Models.Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cpu_production_cpus_cpu_id");

                    b.Navigation("Cpu");
                });
#pragma warning restore 612, 618
        }
    }
}
